### ISSUE TITLE
How deploy your app with the new configurations created by CAMP ?

### ISSUE THREAD

**Issue by fermenreq** [STAMP-project/camp-samples#2]
Hi @vassik , 

The above sources and directories has been generated and my question is how to deploy CityGo with the new configurations ?  

root@osboxes:/home/osboxes/Proyectos/STAMP/WP2_ATOS_USE_CASE/CAMP/camp-samples/atos# ls
ampcompose.yml  build     **compose2**       docker-compose  genimages.yml  **out**   resolmodel.yml  variables.yml~
ampimages.yml   **compose1**  composite.yml  features.yml    images.yml     **repo**  variables.yml

It could be better if we have some steps in the Readme 

Bests,
Fernando

**Comment by vassik** [comment]
@fermenreq please refer to https://github.com/STAMP-project/camp/issues/6

Please do not use this repository anymore.

You can now use the main https://github.com/STAMP-project/camp repository for logging issues. I have moved source code from this repository to https://github.com/STAMP-project/camp/tree/master/samples/stamp
